logging:
  level:
    root: ERROR
    org.springframework: ERROR
    com.sypark.simple: ERROR

server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: plain/text

#management.endpoints.web.exposure.include: "*"
#management.endpoints.jmx.exposure.include: "*"
